/// <reference lib="webworker" />
/// <reference types="vite/client" />

import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";
import { CacheableResponsePlugin } from "workbox-cacheable-response";

declare const self: ServiceWorkerGlobalScope;
declare const __WB_MANIFEST: Array<{ url: string; revision: string | null }>;

// Precache all assets generated by your build process
precacheAndRoute(__WB_MANIFEST);

// Handle client-side navigation
const handler = createHandlerBoundToURL("/index.html");
const navigationRoute = new NavigationRoute(handler, {
  // Don't handle data requests or asset requests
  denylist: [
    /\.[a-z0-9]+$/i, // Exclude URLs ending with file extensions
    /^\/api\//i, // Exclude API requests
    /^\/data\//i // Exclude data requests
  ]
});
registerRoute(navigationRoute);

// Cache static assets
registerRoute(
  ({ request }) =>
    request.destination === "style" ||
    request.destination === "script" ||
    request.destination === "font",
  new StaleWhileRevalidate({
    cacheName: "static-resources"
  })
);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new CacheFirst({
    cacheName: "images",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60 // 30 Days
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200]
      })
    ]
  })
);

// Cache API responses
registerRoute(
  ({ url }) => url.pathname.startsWith("/api/"),
  new NetworkFirst({
    cacheName: "api-responses",
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 // 1 hour
      })
    ]
  })
);

// Handle offline fallback
self.addEventListener("install", (event) => {
  const offlineFallbackPage = "/offline.html";
  event.waitUntil(
    caches.open("offline-cache").then((cache) => {
      return cache.add(offlineFallbackPage);
    })
  );
});

// Clean up old caches
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (
            !["static-resources", "images", "api-responses", "offline-cache"].includes(cacheName)
          ) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});
